version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.docker
    volumes:
      - .:/app
    command: >
      sh -c "sleep 10 && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: myDict
    ports:
      - "3306:3306"
    volumes:
      - mydict_db_data:/var/lib/mysql
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

volumes:
  mydict_db_data:
    driver: local
